export const CATEGORIES = Object.freeze({
    BEST_ACTOR: 'ACTOR IN A LEADING ROLE',
    BEST_ACTRESS: 'ACTRESS IN A LEADING ROLE',
    BEST_SUPPORTING_ACTOR: 'ACTOR IN A SUPPORTING ROLE',
    BEST_SUPPORTING_ACTRESS: 'ACTRESS IN A SUPPORTING ROLE',
    BEST_ORIGINAL_SONG: 'MUSIC (Original Song)',
});